const ingredients = [
  {
    id: 1,
    title: '1 pound oats',
  },
  {
    id: 2,
    title: '6 cucumber',
  },
  {
    id: 3,
    title: '2 eggs',
  },
  {
    id: 4,
    title: 'no MSG',
  },
];

const recipes = [
  {
    id: 1,
    name: 'Flesh Salad',
    discount: '20%',
    price: 55,
    image: require('../../assets/restaurant/yoav-aziz-AiHJiRCwB3w-unsplash.jpeg'),
    ingredients: [
      { id: 1, title: 'Avocado' },
      { id: 2, title: 'Lemon Juice' },
      { id: 3, title: 'Lettace' },
      { id: 4, title: 'Salt and Pepper' },
      { id: 5, title: 'Olive Oil' },
    ],

    description:
      'Salad is more than just soggy iceberg, so if you’ve ever made a salad that tastes bland — you’re making it wrong (and trust us, we’ve all been there). Here are some top tips to transform your salads from sad to sensational.',
    rating: 4.7,
    time: '15 min',
    del_time: '8 min',
    cooking_time: '4 min',
    category: 'Vegetarian',
    area: 'Italian',
    ytId: 'lLC2vnsQfA8',
  },
  {
    id: 2,
    name: 'Toast With Eggs',
    discount: '30%',
    price: 25,
    image: require('../../assets/restaurant/pexels-trang-doan-824635.jpeg'),
    ingredients: [
      { id: 1, title: 'Eggs' },
      { id: 2, title: 'Avocado' },
      { id: 3, title: 'Lettace' },
      { id: 4, title: 'Salt and Pepper' },
      { id: 5, title: 'Toast' },
    ],
    description:
      "Simply put, these are some of my favorite ways to cook eggs because they're all about 5-10 minuets of prep and you end up with something incredibly delish and very customizable to boot. I even really like a cheese scrambled variation of these with jalapeños, but that's for another day. Hopefully you guys enjoyed the recipe and let me know what your go-to breaky eggs and toast are! ENJOY!",
    rating: 4.7,
    time: '10 min',
    del_time: '5 min',
    cooking_time: '3 min',
    category: 'Vegetarian',
    area: 'British',
    ytId: 'WsonsBTQoc0',
  },
  // {
  //   id: 2,
  //   name: "Toast With Eggs",
  //   discount: "30%",
  //   price: 25,
  //   image: require("../../assets/restaurant/pexels-trang-doan-824635.jpeg"),
  //   ingredients,
  //   description:
  //     "Id amet veniam nisi esse ea. Ex est ut cupidatat sint culpa commodo exercitation est magna proident officia laboris. Exercitation laboris ex laborum qui mollit et occaecat deserunt incididunt. Mollit excepteur sunt adipisicing ullamco excepteur non ex proident. Irure laborum enim do fugiat aute amet eu quis amet tempor.",
  //   rating: 4.7,
  //   time: "10 min",
  //   del_time: "5 min",
  //   cooking_time: "3 min",
  // },
  {
    id: 3,
    name: 'Smoked Haddock Kedgeree',
    discount: '10%',
    price: 19,
    image: require('../../assets/restaurant/add_1.jpeg'),
    ingredients: [
      { id: 1, title: 'Butter' },
      { id: 2, title: 'Onion' },
      { id: 3, title: 'Cardamom' },
      { id: 4, title: 'Cinnamon Stick' },
      { id: 5, title: 'Bay Leaf' },
      { id: 6, title: 'Basmati Rice' },
      { id: 7, title: 'Chicken Stock"' },
    ],
    description:
      'Melt 50g butter in a large saucepan about 20cm across, add 1 finely chopped medium onion and cook gently over a medium heat for 5 minutes, until softened but not browned.Stir in 3 split cardamom pods, tsp turmeric, 1 small cinnamon stick and 2 bay leaves, then cook for 1 minute.Tip in 450g basmati rice and stir until it is all well coated in the spicy butter.Pour in 1 litre chicken or fish stock, add ½ teaspoon salt and bring to the boil, stir once to release any rice from the bottom of the pan. Cover with a close-fitting lid, reduce the heat to low and leave to cook very gently for 12 minutes.\r\n\r\nMeanwhile, bring some water to the boil in a large shallow pan. Add 750g un-dyed smoked haddock fillet and simmer for 4 minutes, until the fish is just cooked. Lift it out onto a plate and leave until cool enough to handle.Hard-boil 3 eggs for 8 minutes.\r\n\r\nFlake the fish, discarding any skin and bones. Drain the eggs, cool slightly, then peel and chop.Uncover the rice and remove the bay leaves, cinnamon stick and cardamom pods if you wish to. Gently fork in the fish and the chopped eggs, cover again and return to the heat for 2-3 minutes, or until the fish has heated through.Gently stir in almost all the 3 tbsp chopped fresh parsley, and season with a little salt and black pepper to taste. Serve scattered with the remaining parsley and garnished with 1 lemon, cut into wedges.',
    rating: 4.7,
    time: '12 min',
    del_time: '6 min',
    cooking_time: '2 min',

    category: 'Breakfast',
    area: 'Indian',
    ytId: 'QqdzDCWS4gQ',
  },
  {
    id: 4,
    name: 'Breakfast Potatoes',
    discount: '25%',
    price: 34,
    image: require('../../assets/restaurant/add_2.jpeg'),
    ingredients: [
      { id: 1, title: 'Potatoes' },
      { id: 2, title: 'Olive Oil' },
      { id: 3, title: 'Bacon' },
      { id: 4, title: 'Garlic Clove' },
      { id: 5, title: 'Maple Syrup' },
      { id: 6, title: 'Salt & Pepper' },
    ],
    description:
      "Before you do anything, freeze your bacon slices that way when you're ready to prep, it'll be so much easier to chop!\r\nWash the potatoes and cut medium dice into square pieces. To prevent any browning, place the already cut potatoes in a bowl filled with water.\r\nIn the meantime, heat 1-2 tablespoons of oil in a large skillet over medium-high heat. Tilt the skillet so the oil spreads evenly.\r\nOnce the oil is hot, drain the potatoes and add to the skillet. Season with salt, pepper, and Old Bay as needed.\r\nCook for 10 minutes, stirring the potatoes often, until brown. If needed, add a tablespoon more of oil.\r\nChop up the bacon and add to the potatoes. The bacon will start to render and the fat will begin to further cook the potatoes. Toss it up a bit! The bacon will take 5-6 minutes to crisp.\r\nOnce the bacon is cooked, reduce the heat to medium-low, add the minced garlic and toss. Season once more. Add dried or fresh parsley. Control heat as needed.\r\nLet the garlic cook until fragrant, about one minute.\r\nJust before serving, drizzle over the maple syrup and toss. Let that cook another minute, giving the potatoes a caramelized effect.\r\nServe in a warm bowl with a sunny side up egg!",
    rating: 4.7,
    time: '20 min',
    del_time: '10 min',
    cooking_time: '5 min',
    category: 'Breakfast',
    area: 'Canadian',
    ytId: 'BoD0TIO9nE4',
  },
  {
    id: 5,
    name: 'Copycat Big Mac',
    discount: '25%',
    price: 34,
    image: require('../../assets/restaurant/add_3.jpeg'),
    ingredients: [
      { id: 1, title: 'mustard & ketchup' },
      { id: 2, title: 'beef' },
      { id: 3, title: 'grated onion' },
      { id: 4, title: 'sweet pickle relish' },
      { id: 5, title: 'American cheese' },
      { id: 6, title: 'Salt and black pepper' },
      { id: 7, title: ' sesame seed buns' },
    ],
    description:
      "We're big fans of the Big Mac (after all, it was on the cover of the first Eat This, Not That! book)—or at least the general principle behind it. The thin patties, the layer of American cheese, the special sauce—all of it comes together in a way that makes this burger a convincing icon of the American fast-food establishment. But no one can say the Big Mac is exactly a healthy meal. That's where we come in! There are two main issues with the Big Mac recipe as it stands: The quality of the ingredients is subpar, and the middle bun is absolutely superfluous. We replace the mystery meat with lean ground sirloin, sear it in a cast-iron skillet until beautifully browned, then bring the classic ingredients together inside a single, squishy sesame seed bun.",
    rating: 4.7,
    time: '20 min',
    del_time: '10 min',
    cooking_time: '5 min',
    category: 'FastFood',
    area: 'America',
    // ytId: 'BoD0TIO9nE4',
  },
  {
    id: 6,
    name: 'Shake Shack ',
    discount: '25%',
    price: 34,
    image: require('../../assets/restaurant/add_4.jpeg'),
    ingredients: [
      { id: 1, title: 'mustard & ketchup' },
      { id: 2, title: 'beef' },
      { id: 3, title: 'grated onion' },
      { id: 4, title: 'lettuce leaves' },
      { id: 5, title: 'American cheese' },
      { id: 6, title: 'Salt and black pepper' },
      { id: 7, title: 'amburger potato buns' },
    ],
    description:
      "Yes, pickle brine! When I started to mess around with different Shake Shack sauce recipes, I found that adding pickle brine gave it that familiar Shake Shack sauce taste that I experienced when taste-testing the real thing.Besides the pickle brine in the sauce, the Shake Shack sauce reminded me of a mixture of Sriracha mayo and fry sauce (a mix of mayonnaise and ketchup.) As a base, I made a fry sauce with a touch of mustard and a sprinkle of cayenne pepper to give it a slight kick. Add in a tablespoon of pickle brine from your jar of pickles, and it creates one of the most delectables mayo-based sauces you'll ever have.",
    rating: 4.7,
    time: '20 min',
    del_time: '10 min',
    cooking_time: '5 min',
    category: 'FastFood',
    area: 'America',
    // ytId: 'BoD0TIO9nE4',
  },
  {
    id: 7,
    name: 'Chili Cheese Burrito ',
    discount: '25%',
    price: 34,
    image: require('../../assets/restaurant/add_5.jpeg'),
    ingredients: [
      { id: 1, title: 'mustard & ketchup' },
      { id: 2, title: 'beef' },
      { id: 3, title: 'grated onion' },
      { id: 4, title: ' taco seasoning' },
      { id: 5, title: 'refried beans' },
      { id: 6, title: ' tomato paste' },
      { id: 7, title: ' burrito shells' },
    ],
    description:
      "If you haven't heard of the chili cheese burrito from Taco Bell, there's a reason for it: It's not even on the menu anymore! While this iconic Taco Bell menu item has created quite the following (we're talking an entire fan page on Facebook and a dedicated chili cheese burrito website), it's not something you can get at any ol' Taco Bell anymore. That's why I made a copycat Taco Bell Chili Cheese Burrito recipe! This burrito (also famously known as the 'Chilito') is incredibly easy to make. The ingredients are few, but it's bursting with flavor. One chili-cheese burrito lover on our team says this burrito is beloved because of the chili and cheese portion within it. According to him, the burrito should be at least 50 percent cheese and 50 percent chili.",
    rating: 4.7,
    time: '20 min',
    del_time: '10 min',
    cooking_time: '5 min',
    category: 'FastFood',
    area: 'America',
    // ytId: 'BoD0TIO9nE4',
  },
  {
    id: 8,
    name: 'Swiss Burger ',
    discount: '25%',
    price: 34,
    image: require('../../assets/restaurant/add_6.jpeg'),
    ingredients: [
      { id: 1, title: 'canola oil' },
      { id: 2, title: 'Steak Sauce' },
      { id: 3, title: 'white or cremini mushrooms' },
      { id: 4, title: ' Salt and black pepper' },
      { id: 5, title: 'ground sirloin' },
      { id: 6, title: ' potato buns' },
      { id: 7, title: 'Swiss cheese' },
    ],
    description:
      "The United States is flush with quirky regional burgers, from the pastrami-topped burgers of Utah to the butter burgers of Wisconsin. Our favorite is the Midwestern smashed burger, which involves using a spatula to thwack a ball of ground beef into a thin patty while it cooks in a cast-iron skillet. This style of burger maximizes crust development and helps the beef retain a ton of juiciness. Try it once, and you may never go back to bulky grilled burgers again. Plus, because you only need a cast-iron skillet and a spatula, you can make these burgers year-round, without having to lug out your grill every time you're in the mood for a burger.",
    rating: 4.7,
    time: '20 min',
    del_time: '10 min',
    cooking_time: '5 min',
    category: 'FastFood',
    area: 'Swiss',
    // ytId: 'BoD0TIO9nE4',
  },
  {
    id: 9,
    name: 'Classic Mojito',
    discount: '25%',
    price: 34,
    image: require('../../assets/restaurant/add_7.jpeg'),
    ingredients: [
      { id: 1, title: 'Fresh mint' },
      { id: 2, title: 'Lime juice' },
      { id: 3, title: 'Rum' },
      { id: 4, title: 'Simple syrup' },
      { id: 5, title: 'Soda water' },
    ],
    description:
      'Is there any cocktail more refreshing than a mojito? Of all the classic cocktails, this iconic Cuban drink is one of the greats. Here’s a mojito recipe that’s spot on perfection: not too sweet, bubbly, and minty fresh. Like the margarita, the true version has less sugar and more nuance than what it’s become in bars and pre-made mixes. It’s perfect for sipping on the patio, and just as good in the dead of winter when you’re dreaming of the beach. Here’s exactly how to make a simple mojito! The mojito is a sour cocktail that originates from Havana, Cuba. The origins of the Mojito are cloudy: some say it was invented in the 1500s, others in the 1800’s with the birth of the Bacardi rum company. In any case, its place as an iconic Cuban cocktail was solidified by the 1930’s when Ernest Hemingway helped to popularize the drink. It makes the list of International Bartender Association’s IBA official cocktails. This means that it has an “exact” definition, though of course it is interpreted differently by bartenders all over the world! Here’s what’s in a classic mojito recipe',
    rating: 4.7,
    time: '20 min',
    del_time: '10 min',
    cooking_time: '5 min',
    category: 'Drinks',
    area: 'America',
    // ytId: 'BoD0TIO9nE4',
  },
  {
    id: 10,
    name: 'Gin and Tonic',
    discount: '25%',
    price: 34,
    image: require('../../assets/restaurant/add_8.jpeg'),
    ingredients: [
      { id: 1, title: '1 part gin' },
      { id: 2, title: '2 parts tonic water' },
    ],
    description:
      'Called a “G and T” or gin tonic in some countries, this refreshing drink is made in countries all around the world. The Gin and Tonic was invented in the 1850’s by British soldiers, who mixed gin with their tonic water as a way to drink quinine (which was thought to cure malaria). Tonic water of today no longer has quinine, but the drink stuck around! Naturally, it’s made of two things: 1 part gin, 2 parts tonic water. The gin and tonic is very popular in Spain, called a Gin-Tonic (pronounced “Zcheen tonic”). I studied abroad in Madrid years ago so to me, this drink has a nostalgia that reminds me of sipping in Spain. Speaking of Spain, we’re taking cues from this country to bring you tips on how to make the best gin and tonic',
    rating: 4.7,
    time: '20 min',
    del_time: '10 min',
    cooking_time: '5 min',
    category: 'Drinks',
    area: 'Spain',
    // ytId: 'BoD0TIO9nE4',
  },
  {
    id: 11,
    name: 'New York Sour',
    discount: '25%',
    price: 34,
    image: require('../../assets/restaurant/add_9.jpeg'),
    ingredients: [
      { id: 1, title: 'Bourbon whiskey' },
      { id: 2, title: 'Lemon juice' },
      { id: 3, title: 'maple syrup' },
      { id: 4, title: 'Red wine' },
    ],
    description:
      'The New York Sour is a well-known variation on the whiskey sour that floats a layer of red wine on top. It’s thought to have been invented by a bartender in the 1880’s in Chicago, earning the name the Continental Sour. It was later picked up and made popular by a bartender in New York City, hence its modern name. The whiskey sour is a classic cocktail that’s on the list of International Bartender Association’s IBA official cocktails. Add a layer of wine and you’ve got this classic red wine cocktail:',
    rating: 4.7,
    time: '20 min',
    del_time: '10 min',
    cooking_time: '5 min',
    category: 'Drinks',
    area: 'America',
    // ytId: 'BoD0TIO9nE4',
  },
];

export default recipes;
